## Label Encode 

In [2]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

** define example **

In [3]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = np.array(data)
print(values)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']


** integer encode **

In [6]:
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(values)
integer_encoded = label_encoder.transform(values)
print(integer_encoded)

[0 0 2 0 1 1 2 0 2 1]


## One Hot Encode

In [7]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


** invert first example

In [8]:
inverted = label_encoder.inverse_transform([np.argmax(onehot_encoded[0, :])])
print(inverted)

['cold']
