## Sequence Padding

In [1]:
from keras.preprocessing.sequence import pad_sequences

/home/cbrom/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


** pre-sequence padding **

In [2]:
sequences = [
    [1, 2, 3, 4],
    [1, 2, 3], 
    [1]
]

# pad sequence
padded = pad_sequences(sequences)
print(padded)

[[1 2 3 4]
 [0 1 2 3]
 [0 0 0 1]]


** post-sequence padding **

In [3]:
# pad sequence
padded = pad_sequences(sequences, padding='post')
print(padded)

[[1 2 3 4]
 [1 2 3 0]
 [1 0 0 0]]


## Sequence Truncation

** pre-sequence truncation **

In [4]:
# truncate sequence
truncated = pad_sequences(sequences, maxlen=2)
print(truncated)

[[3 4]
 [2 3]
 [0 1]]


** post-sequence truncation **

In [5]:
# truncate sequence
truncated = pad_sequences(sequences, maxlen=2, truncating='post')
print(truncated)

[[1 2]
 [1 2]
 [0 1]]
